//
//  {name}.hpp
//
//  --------------------------------------------------------------
//
//  This file was generated by the Shadecc tool.
//
//  This code will be overwritten if re-generated and could break things badly if
//  edited manually.
//

#pragma once

#include <Shadecc.hpp>

namespace {name} {{

extern shadecc::ShaderSource source;

}} // namespace {name}