//
//  {name}.hpp
//
//  --------------------------------------------------------------
//
//  This file was generated by the Shadecc tool.
//
//  This code will be overwritten if re-generated and could break things badly if
//  edited manually.
//

#include "{name}.hpp"

#include <cstdint>

namespace {name} {{


static constexpr uint8_t msl_bytes[] = {{
    {msl_bytes}
}};

static constexpr uint8_t hlsl_bytes[] = {{
    {hlsl_bytes}
}};

shadecc::ShaderSource source = {{
    "{name}",
    R"({glsl_src})",
    R"({msl_src})",
    R"({hlsl_src})",
    msl_bytes,
    hlsl_bytes
}};


}} // namespace {name}